### ISSUE TITLE
Организация кода

### ISSUE THREAD

**Issue by dennypenta** [rumyantseva/mif#8]
Привет.
Могли бы вы рассказать об организации исходников в проекта?
Я наблюдаю у вас точку входна, которая является частью исходников, `mif.go`, там же где лежат vendor, .gitignore и прочий шум, который рядом с исходниками, как я считаю, быть не должен.
Могли бы вы посоветовать, как жить?
Я чего-то не понимаю в go-way или при создании этого проекта не было такой задачи?
Спасибо за внимание, всего доброго!

**Comment by rumyantseva** [comment]
Привет! Спасибо за вопрос!
Когда я писала этот код, я не думала, что его будут показывать в качестве примера, так что деление на пакеты и распределение кода по директориям тут, мягко говоря, не идеальное :)
В целом, я думаю, можно выбрать тот подход, который вам кажется более удобным.
Могу предложить посмотреть вот этот проект: https://github.com/takama/k8sapp (автор проекта - мой бывший коллега Игорь, он тоже открыт для вопросов).
В проекте `k8sapp` точка входа находится в директории `cmd`. Как Вы, наверное, знаете, это очень популярный подход в Go-мире. Ну и все остальные пакеты живут в `pkg`. Причем размер пакетов там старались сделать минимальным. Например, в `service` задается базовая конфигурация сервиса (определение конфигов, и хендлеров), в `handlers` лежат только непосредственно сами обработчики запросов и т. д.

**Comment by dennypenta** [comment]
Спасибо за ссылку, очень наглядно.
А могли бы вы подсказать откуда взялся такой подход и где о нем можно почитать? То есть какие плюсы он в себе несет и почему.

**Comment by rumyantseva** [comment]
Где почитать, честно говоря, сразу не скажу (но попробую что-нибудь найти на эту тему).

Мы подсмотрели этот подход в разных проектах (kubernetes, docker, traefik, ...)
В чем удобство: в pkg лежит то, что в той или иной мере является библиотекой. Библиотечный код по возможности разбит на независимые пакеты так, чтобы их можно было переиспользовать каким-то образом или хотя бы скопипастить в новый проект что-то полезное и при этом не тащить кучу ненужного. Ну и опять же разбираться новым людям так проще - посмотреть код + тесты в независимых либах.

В cmd, вообще говоря, лежат все необходимые "точки входа" и внутри могут быть еще несколько директорий - под разные утилиты (например, как в Kubernetes - https://github.com/kubernetes/kubernetes/tree/master/cmd).

Еще один интересный момент - если к сервису предполагается клиент для "внешних" пользователей и по какой-то причине хочется его хранить в том же репозитории, а не в отдельном, то этого клиента как раз лучше завести в отдельной директории в корне, директорию сделать с таким же названием, как сам проект называется (чтобы пути импорта были красивыми и удобными для тех, кто этим клиентом пользуется). Ну и еще важно постараться не использовать ничего из pkg в зависимостях клиента, чтобы пользователю клиента не пришлось никакие лишние зависимости к себе тащить.

**Comment by dennypenta** [comment]
Спасибо, очень помогли.
Моглы бы вы еще рассказать как вы сейчас организовываете тесты в своих проектах?
Держать их в приложение и рядом с каждым файлом наблюдать _test.go считаю не идеальным, хотя с другой стороны читать код всегда легче, так как тесты являются также примерами к коду и ожидаемому поведению.

Если есть возможность с вами/вашими товарищами поучавствовать в open-source проекте - дайте знать.

**Comment by rumyantseva** [comment]
Ну, если это юнит-тесты, то идиоматично их все-таки держать вместе с пакетом. Ну и так, на мой взгляд, все-таки наиболее удобно. Например, если меняешь/добавляешь какую-то функцию, и надо сразу запустить/дописать тест на эту функцию, это удобнее делать, когда тесты где-то рядом. В команде, где я работаю сейчас, вообще всё строится на TDD (прям почти классическом), и мы тесты запускаем постоянно. Но далеко не всегда надо использовать тесты на весь проект целиком, а вот тесты на отдельные пакеты удобнее запускать, когда они рядом.
Но, например, для интеграционных тестов, на мой взгляд, может быть удобно как раз завести даже отдельный репозиторий.

Поучаствовать у нас есть где, да :) 
У нас есть вот такой проект - https://k8s.community, в рамках которого мы разрабатываем вот эту https://github.com/k8s-community кучу добра. В последнее время, мы не очень активно им занимаемся, но там всегда есть над чем поработать, так что мы будем рады новым людям (может, нам новых людей и не хватает для вдохновения).
Про то, что это такое и как оно работает, можно посмотреть запись нашего воркшопа с РИТ++ - https://youtu.be/0ndWw1udpsA?t=7m16s. 
Если интересно - присоединяйтесь к нам в слаке (можно прям в general о себе написать), у нас фактически все коммуникации там. Инвайт можно получить здесь: https://slack.k8s.community.
